server:
  port: 8005

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/ #,http://localhost:8002/eureka/,http://localhost:8003/eureka/

spring:
  application:
    name: service-customer-ribbon

debug: true

logging:
  level:
    root: warn
    org:
      springframework:
        boot:
          autoconfigure: error
        web: info
      hibernate: error
      mybatis: info