server:
  port: 8002

eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:8001/eureka/,http://peer3:8003/eureka/

spring:
  application:
    name: eureka-server-peer2