server:
  port: 8008

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ghosts321/spring-cloud
          search-paths: springcloudconfig
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/ #,http://localhost:8002/eureka/,http://localhost:8003/eureka/
