server:
  port: 8008

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ghosts321/spring-cloud
          search-paths: springcloudconfig
      label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

#关闭安全认证
management:
  #refresh接入点显式暴露出来
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/ #,http://localhost:8002/eureka/,http://localhost:8003/eureka/

logging:
  level:
    root: info
    org:
      springframework:
        boot:
          autoconfigure: error
        web: info
      hibernate: error
      mybatis: info