server:
  port: 8007

spring:
  application:
    name: service-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/ #,http://localhost:8002/eureka/,http://localhost:8003/eureka/

zuul:
  routes:
    api-producer:
      path: /api-producer/**
      serviceId: service-producer
    api-ribbon:
      path: /api-ribbon/**
      serviceId: service-customer-ribbon
    api-feign:
      path: /api-feign/**
      serviceId: service-customer-feign
    api-configclient:
      path: /api-configclient/**
      serviceId: config-client
    github:
      path: /github/**
      url: https://github.com/
    baidu:
      path: /baidu/**
      url: https://baidu.com/
